baseurl = "https://yuru-c.github.io/"
languageCode = "zh-tw"
theme = "terminal"
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.zh]
    title = "yuru's Portfolio"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = "© 2026 yuru"
    menuMore = "顯示更多"
    readMore = "閱讀全文"
    readOtherPosts = "閱讀其他文章"

    [languages.zh.params.logo]
      logoText = "yuru>_"
      logoHomeLink = "/"

    [languages.zh.menu]
      [[languages.zh.menu.main]]
        identifier = "about"
        name = "關於我"
        url = "/about"
      [[languages.zh.menu.main]]
        identifier = "showcase"
        name = "XXX"
        url = "/showcase"
